### ISSUE TITLE
failed to read client configuration template file: open /host/etc/beegfs/beegfs-client.conf: no such file or directory

### ISSUE THREAD

**Issue by titansmc** [ThinkParQ/beegfs-csi-driver#10]
I used to have the controller running on a master node via affinity rule, (version 1.2.0) but now that I have upgraded to v1.2.1 I had to remove the affinity rule otherwise the beegfs container would fail like this:
```
16:59 # kubectl logs -f -n kube-system csi-beegfs-controller-0 beegfs 
E0725 14:57:42.243667       1 main.go:70]  "msg"="Fatal: Failed to initialize driver" "error"="failed to read client configuration template file: open /host/etc/beegfs/beegfs-client.conf: no such file or directory" "fullError"="open /host/etc/beegfs/beegfs-client.conf: no such file or directory\nfailed to read client configuration template file" "goroutine"="main" 
```
So my master nodes never had the beegfs requirements installed (everything that is required to be installed like client) and it always worked, so my question is if there has been any change introduced that we required the controller to be scheduled in a beegfs capable client node, and if not, what could be the issue.

Cheers.

**Comment by gmarks-ntap** [comment]
Hi @titansmc,

The controller service has always had a requirement to be running on a node with the beegfs packages installed, at least for full functionality. There was some additional validation added in v1.2.1 to verify the existence of the beegfs utilities on the nodes running the driver and this validation is where you are now running in to the error. See https://github.com/NetApp/beegfs-csi-driver/commit/420784614e494b07cb6e5de967eb6383da19032f for the particular commit if you're interested.

Thinking about your situation, I'm wondering if you statically provision your volumes? The controller service only really needs to use the beegfs utilities when it dynamically provisions volumes. Before the extra validation was added, the controller service would likely never fail if it was never asked to dynamically create a volume so you may have been unknowingly working around that requirement. If you were using dynamic provisioning prior to v1.2.1 then I'm not currently sure how that was working and additional information might be helpful.

**Comment by titansmc** [comment]
Thanks for the explanation. That was the case, we manually provision an existing volume and make it available in k8s.
All good then!
