### ISSUE TITLE
Request for feedback

### ISSUE THREAD

**Issue by ejweber** [ThinkParQ/beegfs-csi-driver#15]
A couple of months ago, ThinkParQ posted a survey in the BeeGFS newsletter and the BeeGFS user group asking for feedback on the current and future use of BeeGFS in containers and in the cloud (public, hybrid, private, or otherwise). This survey was created in collaboration with the BeeGFS CSI driver maintainers in the hopes of better understanding what features we should add to the 1.x version of the driver (and what a 2.x version of the driver might look like). Unfortunately, the survey didn't receive enough responses to be particularly useful. If you have not already taken the survey please consider doing so at the link below!

[BeeGFS Cloud and Containerization Survey](https://docs.google.com/forms/d/e/1FAIpQLSejJRZm-K5_FG4nRUNkedMyvXyEq1rwl_RcM_rNEIGmMLBF3g/viewform)

**Comment by iamjoemccormick** [comment]
Closing as we've now enabled [GitHub Discussions](https://github.com/ThinkParQ/beegfs-csi-driver/discussions) on the repository.
