### ISSUE TITLE
unable to find metadata node for path:/mnt/beegfs

### ISSUE THREAD

**Issue by GodGirlwsy** [ThinkParQ/beegfs-csi-driver#3]
![image](https://user-images.githubusercontent.com/53068220/155962806-f8f58d3a-b2d2-46bc-93b7-b5a9a75e9e33.png)

**Comment by ejweber** [comment]
Hello @GodGirlwsy. A little more detail would be helpful, but I think I can infer the issue from the logs you have provided.

You appear to be using the static provisioning workflow, in which you do not ask the driver's controller service to create a new BeeGFS directory, but instead ask the driver's node service to mount an existing directory. When using this workflow, you are expected to construct a volumeHandle and place it in your PV. The handle should be formatted like beegfs://sysMgmtdHost/path/to/dir. Presumably you have correctly specified 187.31.0.206 as your sysMgmtdHost and incorrectly (I think) specified /mnt/beegfs as /path/to/dir.

Note that /path/to/dir should be a path rooted within the BeeGFS file system. If you want your container to see the entire BeeGFS file system, this path should simply be / (e.g. beegfs://187.31.0.206/).

/mnt/beegfs is commonly used as the mount point for a BeeGFS file system when using BeeGFS in the traditional way (e.g. systemctl start beegfs-client). Note that it is NOT necessary to mount your BeeGFS file system to a node before using the driver and the driver does NOT make use of any existing mounts.

If you suspect there is something else going on here, or need more assistance, please provide the manifests you used in this example (e.g. PersistentVolume, PersistentVolumeClaim, Pod).

**Comment by ejweber** [comment]
I meant to add a link the the relevant Static Provisioning Workflow documentation:

https://github.com/NetApp/beegfs-csi-driver/blob/master/docs/usage.md#static-provisioning-workflow

**Comment by GodGirlwsy** [comment]
> I meant to add a link the the relevant Static Provisioning Workflow documentation:
> 
> https://github.com/NetApp/beegfs-csi-driver/blob/master/docs/usage.md#static-provisioning-workflow

I change the volumeHandle to beegfs://187.31.0.206/  ,the problem solved，thank you very much！

**Comment by ejweber** [comment]
Glad to hear it! Closing the issue.
